routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('products','ProductsController');

app/Product.php
<?php

namespace App;
use App\User;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
//    protected $table = '';
    protected $guarded=[];
    public function user()
    {
        return $this->belongsTo('App\User');
    }

}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use APP\Product;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * @return bool
     */
    public function products()
    {
        return $this->hasMany('App\Product');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        $user = auth()->user();
        return view('home', [
            'products' => $user->products
        ]);
    }
}

app/Http/Controllers/ProductsController.php
<?php

namespace App\Http\Controllers;

use App\Http\Resources\ProductResource;
use App\Product;

use Illuminate\Contracts\Validation\Validator;
use Illuminate\Http\Request;

class ProductsController extends Controller
{

//    public function __construct()
//    {
//        $this->middleware('auth', ['except' => ['show', 'index']]);
//    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = Product::all();
//        return  ProductResource::collection($products);
        return view('product.index', [
            'products' => $products
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('product.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $this->validate($request, [
            'brand' => 'required',
            'modelName' => 'required',
            'price' => 'required'
        ]);
        $product = new Product($data);
        $product->user_id =1;
//        $product->user_id = auth()->user()->id;

//        $validators = Validator::($request->all(),[
//            'brand' => 'required',
//            'modelName' => 'required',
//            'price' => 'required'
//        ]);
        $product->save();
        return redirect('products');

    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $product = Product::find($id);
        return view('product.show', [
            'product' => $product
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $product = Product::find($id);

        return view('product.edit', [
            'product' => $product
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data = $this->validate($request, [
            'brand' => 'required',
            'modelName' => 'required',
            'price' => 'required'
        ]);
        $product = Product::Find($id);
        $product->update($data);
        return redirect('home');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $product = Product::find($id);
        $product->delete();
        return redirect('/home');
    }
}

resources/views/Product/create.blade.php
@extends('layouts.app')

@section('content')

        {!! Form::open(['action'=> 'ProductsController@store','method'=>'POST']) !!}
        <div class="row d-flex py-2">
            <div class="col-1 align-self-center">
                {{Form::label('brand', 'Brand', ['class'=>'m-0'])}}
            </div>
            <div class="col-6">
                {{Form::text('brand','', ['class'=>'form-control'])}}
            </div>
        </div>
        <div class="row d-flex py-2">
            <div class="col-1 align-self-center">
                {{Form::label('modelName', 'Model', ['class'=>'m-0'])}}
            </div>
            <div class="col-6">
                {{Form::text('modelName','', ['class'=>'form-control'])}}
            </div>
        </div>
        <div class="row d-flex py-2">
            <div class="col-1 align-self-center">
                {{Form::label('price', 'Price', ['class'=>'m-0'])}}
            </div>
            <div class="col-6">
                {{Form::text('price','', ['class'=>'form-control'])}}
            </div>
        </div>

        {!! Form::submit('Submit',['class'=> 'btn btn-success']) !!}

        {!! Form::close() !!}



@endsection

resources/views/Product/edit.blade.php
@extends('layouts.app')

@section('content')
    {!! Form::open(['action'=> ['ProductsController@update',$product->id],'method'=>'PUT']) !!}
    <div class="row d-flex py-2">
        <div class="col-1 align-self-center">
            {{Form::label('brand', 'Brand', ['class'=>'m-0'])}}
        </div>
        <div class="col-6">
            {{Form::text('brand',$product->brand, ['class'=>'form-control'])}}
        </div>
    </div>
    <div class="row d-flex py-2">
        <div class="col-1 align-self-center">
            {{Form::label('modelName', 'Model', ['class'=>'m-0'])}}
        </div>
        <div class="col-6">
            {{Form::text('modelName',$product->modelName, ['class'=>'form-control'])}}
        </div>
    </div>
    <div class="row d-flex py-2">
        <div class="col-1 align-self-center">
            {{Form::label('price', 'Price', ['class'=>'m-0'])}}
        </div>
        <div class="col-6">
            {{Form::text('price',$product->price, ['class'=>'form-control'])}}
        </div>
    </div>

    {!! Form::submit('Submit',['class'=> 'btn btn-success']) !!}

    {!! Form::close() !!}


@endsection

resources/views/Product/index.blade.php
@extends('layouts.app')

@section('content')
    @if(count($products)>0)
    <table class="table">
        <thead>
        <tr>
            <th scope="col">S.N.</th>
            <th scope="col">Posted By</th>
            <th scope="col">Brand</th>
            <th scope="col">Model</th>
            <th scope="col">Price</th>

        </tr>
        </thead>
        <tbody>

        @foreach($products as $product)
            <tr>

                    <th scope="row">{{$product->id}}

                    </th>
                    <td>
                        {{$product->user->name}}
                    </td>
                    <td>
                        {{$product->brand}}
                    </td>
                    <td>
                        {{$product->modelName}}
                    </td>
                    <td>
                        {{$product->price}}
                    </td>
                <td>
                    <a href="{{route('products.show',[$product->id])}}" class="btn btn-primary">View</a>
                </td>


            </tr>

        @endforeach
        </tbody>
    </table>
    @endif
@endsection

resources/views/Product/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                   <div class="title-wrap">
                       {{$product->brand.' '.$product->modelName}}
                   </div>
                    <div class="text-wrap">
                        <small class="">Posted on {{$product->created_at}} by {{$product->user->name}}</small>

                    </div>

                </div>

                <div class="card-body">
                    <div mt-5>Price: {{$product->price}}</div>

                </div>
            </div>
        </div>
    </div>



@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')

    <div class="row justify-content-center">
        <div class="col-md-10">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                    @if(count($products)>0)

                        <h3>Your ads</h3>
                            <table class="table">
                                <thead>
                                <tr>
                                    <th scope="col">S.N.</th>
                                    <th scope="col">Brand</th>
                                    <th scope="col">Model</th>
                                    <th scope="col">Price</th>
                                    <th></th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($products as $product)
                                    <tr>
                                        <th scope="row">
                                            {{$product->id}}
                                        </th>
                                        <td>
                                            {{$product->brand}}
                                        </td>
                                        <td>
                                            {{$product->modelName}}
                                        </td>
                                        <td>
                                            {{$product->price}}
                                        </td>
                                        <td>
                                            <div class="d-flex justify-content-end">
                                                <a href="\products\{{$product->id}}\edit" class="btn btn-primary mr-1">Edit</a>
                                                {!! Form::open(['action' => ['ProductsController@destroy',$product->id],'method' => 'DELETE','class'=>'d-inline']) !!}
                                                {{Form::submit('Delete',['class'=> "btn btn-danger "])}}

                                                {!!Form::close()!!}
                                            </div>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                    @endif

                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
{{--        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">--}}
{{--            <div class="container">--}}
{{--                <a class="navbar-brand" href="{{ url('/') }}">--}}
{{--                    {{ config('app.name', 'Laravel') }}--}}
{{--                </a>--}}
{{--                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">--}}
{{--                    <span class="navbar-toggler-icon"></span>--}}
{{--                </button>--}}

{{--                <div class="collapse navbar-collapse" id="navbarSupportedContent">--}}
{{--                    <!-- Left Side Of Navbar -->--}}
{{--                    <ul class="navbar-nav mr-auto">--}}
{{--                        <li class="nav-item"><a href="\home" class="nav-link">Home</a></li>--}}
{{--                        <li class="nav-item"><a href="{{route('products.index')}}" class="nav-link">Products</a></li>--}}
{{--                        <li class="nav-item"><a href="{{route('products.create')}}" class="nav-link">Create</a></li>--}}
{{--                    </ul>--}}

{{--                    <!-- Right Side Of Navbar -->--}}
{{--                    <ul class="navbar-nav ml-auto">--}}
{{--                        <!-- Authentication Links -->--}}
{{--                        @guest--}}
{{--                            <li class="nav-item">--}}
{{--                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>--}}
{{--                            </li>--}}
{{--                            @if (Route::has('register'))--}}
{{--                                <li class="nav-item">--}}
{{--                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>--}}
{{--                                </li>--}}
{{--                            @endif--}}
{{--                        @else--}}
{{--                            <li class="nav-item dropdown">--}}
{{--                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>--}}
{{--                                    {{ Auth::user()->name }} <span class="caret"></span>--}}
{{--                                </a>--}}

{{--                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">--}}
{{--                                    <a class="dropdown-item" href="{{ route('logout') }}"--}}
{{--                                       onclick="event.preventDefault();--}}
{{--                                                     document.getElementById('logout-form').submit();">--}}
{{--                                        {{ __('Logout') }}--}}
{{--                                    </a>--}}

{{--                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">--}}
{{--                                        @csrf--}}
{{--                                    </form>--}}
{{--                                </div>--}}
{{--                            </li>--}}
{{--                        @endguest--}}
{{--                    </ul>--}}
{{--                </div>--}}
{{--            </div>--}}
{{--        </nav>--}}

        @include('layouts.header')
        <main class="py-4">
            <div class="container">
                @include('layouts.message')
                @yield('content')
            </div>
        </main>
    </div>
</body>
</html>

resources/views/layouts/header.blade.php
<header>
    <div id="main-navbar" class="navbar navbar-expand-lg">

        <div class="left-content">
            <div class="logo">
                <a class="" href="\">
                    <img src="{{ asset('images\logo.png') }}">
                </a>
            </div>
            <div class="input-group search-bar">
                <input type="text" class="form-control" placeholder="Search">
                <div class="input-group-append">
                    <button class="btn btn-primary" type="button">
                        <i class="fa fa-search"></i>
                    </button>
                </div>
            </div>
        </div>
        <div class="right-content">
            <nav id="nav">
                <ul class="nav-links">
                    <li ><a href="\home" class="nav-link">Home</a></li>
                    <li><a href="{{route('products.index')}}" class="nav-item nav-link">Products</a></li>
                    <li ><a href="{{route('products.create')}}" class="nav-item nav-link">Create</a></li>

                <!-- Authentication Links -->
                @guest
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                    </li>
                    @if (Route::has('register'))
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                        </li>
                    @endif
                @else
                    <li class="nav-item dropdown">
                        <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button"
                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                            {{ Auth::user()->name }} <span class="caret"></span>
                        </a>

                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{{ route('logout') }}"
                               onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                {{ __('Logout') }}
                            </a>

                            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                @csrf
                            </form>
                        </div>
                    </li>
                    @endguest
                    </ul>
            </nav>
        </div>

    </div>
</header>

resources/views/layouts/message.blade.php
@if(count($errors)>0)
    @foreach($errors->all() as $error)
        <div class="alert alert-danger">
            {{$error}}
        </div>
        @endforeach
    @endif

@if(session('success'))
    <div class="alert alter-success">
        {{session('success')}}
    </div>
    @endif

@if(session('error'))
    <div class="alert alter-danger">
        {{session('error')}}
    </div>
    @endif